# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{postgresql_port}}"
    priv: "{{item.priv | default(omit)}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  when: postgresql_user_privileges|length > 0 and item.type is not defined
  with_items: "{{ postgresql_user_privileges }}"

- name: PostgreSQL | Update the user privileges 2
  postgresql_privs:
    db: "{{ item.db }}"
    privs: "{{ item.priv }}"
    type: "{{ item.type }}"
    objs: "{{ item.objs }}"
    role: "{{ item.name }}"
    schema: "{{ item.schema | default(omit) }}"
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  when: postgresql_user_privileges|length > 0 and item.type is defined
  with_items: "{{postgresql_user_privileges}}"